### ISSUE TITLE
Cannot build image using rethinkdb_exporter:v.0.5.0

### ISSUE THREAD

**Issue by shivgana** [oliver006/rethinkdb_exporter#25]
While using rethinkdb_exporter:v0.5.0 to build new image , it throws error "/bin/sh not found in $PATH" on every command specified in RUN.

**Comment by oliver006** [comment]
I don't know what this means - can you provide more information please?

**Comment by shivgana** [comment]
Suppose I want use rethinkdb_exporter as base image and create a new image.
```dockerfile
FROM oliver006/rethinkdb_exporter:v0.5.0
RUN echo "copy the files"
COPY . /
CMD .....
```
When I run docker build , it throws error "/bin/sh not found in $PATH" at RUN step.

**Comment by oliver006** [comment]
Ah, I see, makes sense now.
Check the Dockerfile here: 
https://github.com/oliver006/rethinkdb_exporter/blob/master/Dockerfile#L20

`FROM scratch as scratch`

It's using `scratch` as the base container for the exporter image so there's no shell in there, nothing.
Try without the echo command.

**Comment by shivgana** [comment]
What is solution for chown command? Like below dockerfile
```dockerfile
FROM oliver006/rethinkdb_exporter:v0.5.0
RUN chown -R <user>:<user> /bin/rethinkdb_exporter
CMD ....
```

While building image above dockerfile same issue occurred.
Error: "/bin/sh not found in $PATH"

**Comment by oliver006** [comment]
The short answer is: don't do that.
The longer answer is: have a look at the rethinkdb_exporter Dockerfile. It first uses a build container (right now golang 1.16) that has a shell and all the other good stuff that's needed to build the exporter. That's where the chown command should be run. The container to run the exporter is the minimal `scratch` container to reduce the attack surface and risk for security issues, that's why there's no shell and nothing else.
The easiest way to address your problem might just be to build the exporter from scratch yourself, just like in the provided Dockerfile.
